# Use the base Node.js image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy necessary files from the correct location
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the migration script and other necessary files
COPY . ./

# Run migration script
CMD ["node", "scripts/migrate-data.ts"]
